// Generated by lsc from glob-subset.ts

datatype Option<T> = None | Some(value: T)

function {:axiom} parseSegments(glob: string): Option<seq<Segment>>

datatype Segment = literal(value: string) | star | globstar

// ───────────────────────────────────────────────────────────────────────────
// Hand-written verification core for glob set-containment SOUNDNESS.
//
// Not emitted from glob-subset.ts: a ghost matching predicate can't be written
// as a TS `//@` spec, so it lives here ("deep specs migrate to .dfy"). The
// TypeScript keeps only `//@ verify` + an `//@ ensures` that the method computes
// exactly `segMatchSpec` below; the soundness of `segMatchSpec` is proved here.
//
// TRUST BOUNDARY: `glmatch` is our model of how a literal/`*`/`**` segment glob
// matches a concrete path. The runtime matcher is picomatch; we assume `glmatch`
// faithfully captures picomatch on this fragment — which is the ONLY fragment
// `parseSegments` accepts (every other metacharacter is rejected), so the trust
// surface is exactly this predicate.
// ───────────────────────────────────────────────────────────────────────────

// A concrete path is a sequence of literal segments (a secret path split on
// "/"). `glmatch(g, gi, path)` holds iff the glob suffix g[gi..] matches the
// whole `path`: `**` matches any number (>= 0) of segments, `*` matches exactly
// one, a literal matches an identical segment.
predicate glmatch(g: seq<Segment>, gi: nat, path: seq<string>)
  requires gi <= |g|
  decreases |g| - gi
{
  if gi == |g| then path == []
  else match g[gi]
    case globstar   => exists k: nat | k <= |path| :: glmatch(g, gi + 1, path[k..])
    case star       => |path| > 0 && glmatch(g, gi + 1, path[1..])
    case literal(v) => |path| > 0 && path[0] == v && glmatch(g, gi + 1, path[1..])
}

// Pure-functional mirror of the `segmentMatch` method. The method carries a
// loop, so it can't be named in specs; this function can, and the method's
// `//@ ensures` certifies it computes exactly this.
function segMatchSpec(parent: seq<Segment>, subset: seq<Segment>, pi: nat, si: nat): bool
  requires pi <= |parent| && si <= |subset|
  decreases (|parent| - pi) + (|subset| - si)
{
  if pi >= |parent| && si >= |subset| then true
  else if pi < |parent| && parent[pi].globstar? then
    segMatchSpec(parent, subset, pi + 1, si)
      || (si < |subset| && segMatchSpec(parent, subset, pi, si + 1))
  else if pi >= |parent| then false
  else if si >= |subset| then
    (forall j :: pi <= j < |parent| ==> parent[j].globstar?)
  else match parent[pi]
    case star        => !subset[si].globstar? && segMatchSpec(parent, subset, pi + 1, si + 1)
    case literal(pv) => subset[si].literal? && subset[si].value == pv && segMatchSpec(parent, subset, pi + 1, si + 1)
    case globstar    => false  // unreachable (handled above); keeps the match total
}

// A suffix of all-globstars matches the empty path.
lemma EmptyMatchesAllGlobstar(g: seq<Segment>, gi: nat)
  requires gi <= |g|
  requires forall j :: gi <= j < |g| ==> g[j].globstar?
  ensures glmatch(g, gi, [])
  decreases |g| - gi
{
  if gi < |g| {
    EmptyMatchesAllGlobstar(g, gi + 1);
    var e: seq<string> := [];
    assert e[0..] == e;
    assert glmatch(g, gi + 1, e[0..]);   // witness k = 0
  }
}

// Under a parent globstar, if subset[si+1..] is contained in parent[pi..], then
// so is subset[si..] — the globstar absorbs whatever subset[si] consumes.
lemma GlobstarAbsorbSubset(parent: seq<Segment>, subset: seq<Segment>, pi: nat, si: nat, path: seq<string>)
  requires pi < |parent| && parent[pi].globstar?
  requires si < |subset|
  requires forall p :: glmatch(subset, si + 1, p) ==> glmatch(parent, pi, p)
  requires glmatch(subset, si, path)
  ensures glmatch(parent, pi, path)
{
  match subset[si] {
    case globstar =>
      var j: nat :| j <= |path| && glmatch(subset, si + 1, path[j..]);
      assert glmatch(parent, pi, path[j..]);
      var m: nat :| m <= |path[j..]| && glmatch(parent, pi + 1, path[j..][m..]);
      assert path[j..][m..] == path[j + m..];
      assert glmatch(parent, pi + 1, path[j + m..]);   // witness k = j + m
    case star =>
      assert glmatch(subset, si + 1, path[1..]);
      assert glmatch(parent, pi, path[1..]);
      var m: nat :| m <= |path[1..]| && glmatch(parent, pi + 1, path[1..][m..]);
      assert path[1..][m..] == path[1 + m..];
      assert glmatch(parent, pi + 1, path[1 + m..]);   // witness k = 1 + m
    case literal(v) =>
      assert glmatch(subset, si + 1, path[1..]);
      assert glmatch(parent, pi, path[1..]);
      var m: nat :| m <= |path[1..]| && glmatch(parent, pi + 1, path[1..][m..]);
      assert path[1..][m..] == path[1 + m..];
      assert glmatch(parent, pi + 1, path[1 + m..]);   // witness k = 1 + m
  }
}

// SOUNDNESS: if segMatchSpec is true, every concrete path matched by the subset
// glob suffix is also matched by the parent glob suffix.
lemma SegMatchSpecSound(parent: seq<Segment>, subset: seq<Segment>, pi: nat, si: nat)
  requires pi <= |parent| && si <= |subset|
  ensures segMatchSpec(parent, subset, pi, si) ==>
          forall path :: glmatch(subset, si, path) ==> glmatch(parent, pi, path)
  decreases (|parent| - pi) + (|subset| - si)
{
  if !segMatchSpec(parent, subset, pi, si) { return; }
  if pi >= |parent| && si >= |subset| { return; }   // both sides reduce to (path == [])

  if pi < |parent| && parent[pi].globstar? {
    if segMatchSpec(parent, subset, pi + 1, si) {
      SegMatchSpecSound(parent, subset, pi + 1, si);
      forall path | glmatch(subset, si, path) ensures glmatch(parent, pi, path) {
        assert glmatch(parent, pi + 1, path);   // IH
        assert path[0..] == path;               // witness k = 0
        assert glmatch(parent, pi + 1, path[0..]);
      }
    } else {
      SegMatchSpecSound(parent, subset, pi, si + 1);
      forall path | glmatch(subset, si, path) ensures glmatch(parent, pi, path) {
        GlobstarAbsorbSubset(parent, subset, pi, si, path);
      }
    }
    return;
  }
  if pi >= |parent| { return; }

  if si >= |subset| {
    EmptyMatchesAllGlobstar(parent, pi);
    forall path | glmatch(subset, si, path) ensures glmatch(parent, pi, path) {
      // glmatch(subset, |subset|, path) ==> path == [], and parent[pi..] all globstar
    }
    return;
  }

  // parent[pi] is star or literal (not globstar); subset[si] consumes one segment
  match parent[pi] {
    case star =>
      SegMatchSpecSound(parent, subset, pi + 1, si + 1);
      forall path | glmatch(subset, si, path) ensures glmatch(parent, pi, path) {
        assert glmatch(subset, si + 1, path[1..]);
        assert glmatch(parent, pi + 1, path[1..]);   // IH
      }
    case literal(pv) =>
      SegMatchSpecSound(parent, subset, pi + 1, si + 1);
      forall path | glmatch(subset, si, path) ensures glmatch(parent, pi, path) {
        assert path[0] == pv;
        assert glmatch(subset, si + 1, path[1..]);
        assert glmatch(parent, pi + 1, path[1..]);   // IH
      }
    case globstar =>
      // unreachable: parent[pi] is not globstar in this branch
  }
}

// End-to-end corollary: the method's certified result (res == segMatchSpec)
// implies soundness. A caller combines `segmentMatch`'s `//@ ensures` with this.
lemma SegmentMatchSound(parent: seq<Segment>, subset: seq<Segment>, pi: nat, si: nat, res: bool)
  requires pi <= |parent| && si <= |subset|
  requires res == segMatchSpec(parent, subset, pi, si)
  ensures res ==> forall path :: glmatch(subset, si, path) ==> glmatch(parent, pi, path)
{
  SegMatchSpecSound(parent, subset, pi, si);
}

method segmentMatch(parent: seq<Segment>, subset: seq<Segment>, pi: int, si: int) returns (res: bool)
  requires (0 <= pi)
  requires (pi <= |parent|)
  requires (0 <= si)
  requires (si <= |subset|)
  ensures (res == segMatchSpec(parent, subset, pi, si))
  decreases ((|parent| - pi) + (|subset| - si))
{
  if ((pi >= |parent|) && (si >= |subset|)) {
    return true;
  }
  if ((pi < |parent|) && parent[pi].globstar?) {
    var i_t0 := segmentMatch(parent, subset, (pi + 1), si);
    if i_t0 {
      return true;
    }
    if (si < |subset|) {
      var i_t1 := segmentMatch(parent, subset, pi, (si + 1));
      return i_t1;
    }
    return false;
  }
  if (pi >= |parent|) {
    return false;
  }
  if (si >= |subset|) {
    var i := pi;
    while (i < |parent|)
      invariant (pi <= i)
      invariant (i <= |parent|)
      invariant forall j: int :: ((pi <= j) ==> (j < i) ==> parent[j].globstar?)
      decreases (|parent| - i)
    {
      if (!parent[i].globstar?) {
        return false;
      }
      i := (i + 1);
    }
    return true;
  }
  var pSeg := parent[pi];
  var sSeg := subset[si];
  match pSeg {
    case star =>
      match sSeg {
        case globstar =>
          return false;
        case _ =>
          var i_t2 := segmentMatch(parent, subset, (pi + 1), (si + 1));
          return i_t2;
      }
    case literal(i_pSeg_value) =>
      match sSeg {
        case literal(i_sSeg_value) =>
          if (i_sSeg_value != i_pSeg_value) {
            return false;
          }
          var i_t3 := segmentMatch(parent, subset, (pi + 1), (si + 1));
          return i_t3;
        case _ =>
          return false;
      }
    case globstar =>
      return false;
  }
}
